#lang racket/base

;; Bezel binding generator: JSON class specs → C++ shim + Racket FFI.
;;
;; The handwritten core (bezel-lib + bezel-shim/src) covers the common
;; widgets with hand-tuned ergonomics. Scale-up coverage — the long tail
;; of the Qt API — is spec-driven, exactly like the mature bindings
;; (PySide/Shiboken, PyQt/SIP, Qtah) do it:
;;
;;   racket tools/generator/generate.rkt tools/generator/specs/*.json
;;
;; Emits:
;;   bezel-shim/src/generated/<module>_gen.cpp   (constructors + methods)
;;   bezel-lib/generated/<module>_gen.rkt        (bindings)
;;
;; The CMake config globs src/generated/*.cpp; require the generated
;; .rkt from bezel-lib/main.rkt, then rebuild (`cmake --build`,
;; `raco make`).
;;
;; Spec format (JSON):
;; {
;;   "class":  "QDial",
;;   "module": "dial",
;;   "header": "QDial",
;;   "constructors": [ { "c-name": "dial_new", "args": ["parent"] } ],
;;   "methods": [
;;     { "c-name": "dial_set_notches", "qt": "setNotchesVisible", "args": ["bool"] },
;;     { "c-name": "dial_notches"  "qt": "notchesVisible"  "ret": "bool" }
;;   ],
;;   "signals": ["valueChanged(int)"]
;; }
;;
;; Arg types: "parent" (widget handle), "widget", "string", "int",
;; "double", "bool".

(require json
         racket/file
         (only-in racket/path path-only)
         racket/format
         racket/list
         racket/match
         racket/port
         racket/string)

;; ---- type maps -------------------------------------------------------------

(define (cpp-type t)
  (match t
    ["parent" "bezel_handle"]
    ["widget" "bezel_handle"]
    ["string" "const char*"]
    ["int"    "int"]
    ["double" "double"]
    ["bool"   "int"]))

(define (cpp-ret t)
  (match t
    ["string" "const char*"]
    ["int"    "int"]
    ["double" "double"]
    ["bool"   "int"]))

(define (rkt-type t)
  (match t
    ["parent" "_bezel-handle"]
    ["widget" "_bezel-handle"]
    ["string" "_string/utf-8"]
    ["int"    "_int"]
    ["double" "_double"]
    ["bool"   "_int"]))

;; C++ expression for passing numbered input i of logical type t to Qt.
(define (c-symbol kebab)
  (string->symbol (string-replace (symbol->string kebab) "-" "_")))

(define (cpp-pass t i)
  (match t
    ["string" (format "q_str~a" i)]
    ["bool"   (format "(in~a != 0)" i)]
    [_        (format "in~a" i)]))

;; ---- shim emitter ----------------------------------------------------------

(define (emit-shim spec)
  (define class (hash-ref spec 'class))
  (define module (hash-ref spec 'module))
  (define header (hash-ref spec 'header))
  (define ctors (hash-ref spec 'constructors '()))
  (define methods (hash-ref spec 'methods '()))
  (define out (open-output-string))
  (define (p . xs) (apply fprintf out xs))

  (p "// <~a>_gen.cpp — generated by tools/generator; edit the spec instead.\n\n" module)
  (p "#include \"../internal.h\"\n\n#include <~a>\n\n" header)
  (p "namespace {\n\nusing namespace bezel;\n\n")
  (p "~a* resolve_obj(bezel_handle h, const char* what) {\n" class)
  (p "    return resolve_as<~a>(h, what);\n}\n\n" class)
  (p "QWidget* resolve_parent(bezel_handle h, const char* what) {\n")
  (p "    return h ? resolve_as<QWidget>(h, what) : nullptr;\n}\n\n")
  (p "}  // namespace\n\nusing namespace bezel;\n\nextern \"C\" {\n\n")

  ;; constructors
  (for ([c ctors])
    (define cname (string-replace (hash-ref c 'c-name) "-" "_"))
    (define args (hash-ref c 'args '()))
    (p "BEZEL_EXPORT bezel_handle ~a(" cname)
    (unless (null? args)
      (p (string-join
          (for/list ([t args] [i (in-naturals)]) (format "~a in~a" (cpp-type t) i))
          ", ")))
    (p ") {\n")
    (p "    return on_gui([=]() -> bezel_handle {\n")
    (for ([t args] [i (in-naturals)])
      (when (equal? t "string")
        (p "        const QString q_str~a = QString::fromUtf8(in~a ? in~a : \"\");\n" i i i)))
    (define ctor-args
      (string-join
       (for/list ([t args] [i (in-naturals)])
         (match t
           ["parent" (format "resolve_parent(in~a, \"~a\")" i cname)]
           [_ (cpp-pass t i)]))
       ", "))
    (p "        return register_object(new ~a(~a));\n" class ctor-args)
    (p "    });\n}\n\n"))

  ;; methods
  (for ([m methods])
    (define mname (string-replace (hash-ref m 'c-name) "-" "_"))
    (define qt (hash-ref m 'qt))
    (define margs (hash-ref m 'args '()))
    (define ret (hash-ref m 'ret #f))
    (p "BEZEL_EXPORT ~a ~a(bezel_handle h~a) {\n"
       (if ret (cpp-ret ret) "int")
       mname
       (string-join
        (for/list ([t margs] [i (in-naturals)]) (format ", ~a in~a" (cpp-type t) i))
        ""))
    (p "    return on_gui([=]() -> ~a {\n" (if ret (cpp-ret ret) "int"))
    (for ([t margs] [i (in-naturals)])
      (when (equal? t "string")
        (p "        const QString q_str~a = QString::fromUtf8(in~a ? in~a : \"\");\n" i i i)))
    (define call-args
      (string-join (for/list ([t margs] [i (in-naturals)]) (cpp-pass t i)) ", "))
    (cond
      [ret
       (p "        ~a* obj = resolve_obj(h, \"~a\");\n" class mname)
       (p "        if (!obj) return ~a;\n"
          (match ret ["double" "-1.0"] ["string" "nullptr"] [_ "-1"]))
       (match ret
         ["string" (p "        return strdup_q(obj->~a(~a));\n" qt call-args)]
         ["bool"   (p "        return obj->~a(~a) ? 1 : 0;\n" qt call-args)]
         [_        (p "        return obj->~a(~a);\n" qt call-args)])]
      [else
       (p "        ~a* obj = resolve_obj(h, \"~a\");\n" class mname)
       (p "        if (!obj) return 0;\n")
       (p "        obj->~a(~a);\n" qt call-args)
       (p "        return 1;\n")])
    (p "    });\n}\n\n"))

  (p "}  // extern \"C\"\n\n")
  (get-output-string out))

;; ---- racket emitter ---------------------------------------------------------

(define (emit-racket spec)
  (define ctors (hash-ref spec 'constructors '()))
  (define methods (hash-ref spec 'methods '()))
  (define module (hash-ref spec 'module))
  (define out (open-output-string))
  (define (p . xs) (apply fprintf out xs))

  (p "#lang racket/base\n\n")
  (p ";; Generated by tools/generator from specs/~a.json — edit the spec.\n\n" module)
  (p "(provide")
  (for ([c ctors]) (p "\n         ~a" (hash-ref c 'c-name)))
  (for ([m methods]) (p "\n         ~a" (hash-ref m 'c-name)))
  (p ")\n\n")
  (p "(require ffi/unsafe\n")
  (p "         racket/string\n")
  (p "         \"../private/ctypes.rkt\"\n")
  (p "         \"../private/errors.rkt\"\n")
  (p "         \"../private/objects.rkt\"\n")
  (p "         \"../private/lib.rkt\")\n\n")
  (p ";; Each binding: raw:<kebab> looks up the snake_case C symbol; the\n")
  (p ";; public wrapper below is named <kebab>.\n\n")

  (for ([c ctors])
    (define kebab (hash-ref c 'c-name))
    (define snake (string-replace kebab "-" "_"))
    (define args (hash-ref c 'args '()))
    (define has-parent (member "parent" args))
    (define parent-idx (if has-parent (index-of args "parent") #f))
    (p "(define raw:~a (get-ffi-obj '~a bezel-lib (_fun ~a -> _bezel-handle)))\n"
       kebab snake
       (string-join (for/list ([t args]) (rkt-type t)) " "))
    (p "(define (~a~a)\n" kebab
       (string-join (for/list ([t args] [i (in-naturals)])
                      (format " [v~a ~a]" i
                              (match t
                                ["string" "\"\""]
                                ["double" "0.0"]
                                ["int" "0"]
                                [_ "#f"])))
                    ""))
    (p "  (require-application)\n")
    (p "  (wrap-handle (ok-handle '~a (raw:~a~a))\n"
       (string->symbol kebab) (string->symbol kebab)
       (string-join (for/list ([t args] [i (in-naturals)])
                      (if (equal? t "parent") (format " (and v~a (ptr-of v~a))" i i) (format " v~a" i)))
                    ""))
    (p "               'widget ~a))\n\n"
       (if has-parent (format "(not v~a)" parent-idx) "#t")))

  (for ([m methods])
    (define kebab (hash-ref m 'c-name))
    (define snake (string-replace kebab "-" "_"))
    (define margs (hash-ref m 'args '()))
    (define ret (hash-ref m 'ret #f))
    (define call-args
      (format "(ptr-of o)~a"
              (string-join
               (for/list ([t margs] [i (in-naturals)])
                 (format " ~a" (if (equal? t "bool") (format "(if v~a 1 0)" i) (format "v~a" i))))
               "")))
    (p "(define raw:~a (get-ffi-obj '~a bezel-lib (_fun _bezel-handle~a -> ~a)))\n"
       kebab snake
       (string-join (for/list ([t margs]) (format " ~a" (rkt-type t))) "")
       (match ret ["string" "_pointer"] [_ (if ret (rkt-type ret) "_int")]))
    (cond
      [(equal? ret "string")
       (p "(define (~a o~a)\n" (string->symbol kebab)
          (string-join (for/list ([t margs] [i (in-naturals)]) (format " v~a" i)) ""))
       (p "  (require-alive! '~a o)\n" (string->symbol kebab))
       (p "  (define ptr (ok-string '~a (raw:~a~a)))\n"
          (string->symbol kebab) (string->symbol kebab) call-args)
       (p "  (begin0 (cstring->string/utf8 ptr)\n    (bezel-free ptr)))\n\n")]
      [(equal? ret "bool")
       (p "(define (~a o~a)\n" (string->symbol kebab)
          (string-join (for/list ([t margs] [i (in-naturals)]) (format " v~a" i)) ""))
       (p "  (require-alive! '~a o)\n" (string->symbol kebab))
       (p "  (define r (raw:~a~a))\n" (string->symbol kebab) call-args)
       (p "  (cond [(= r -1) (raise-bezel-error '~a)]\n        [(= r 1) #t]\n        [else #f]))\n\n"
          (string->symbol kebab))]
      [ret
       (p "(define (~a o~a)\n" (string->symbol kebab)
          (string-join (for/list ([t margs] [i (in-naturals)]) (format " v~a" i)) ""))
       (p "  (require-alive! '~a o)\n" (string->symbol kebab))
       (p "  (raw:~a~a))\n\n" (string->symbol kebab) call-args)]
      [else
       (p "(define (~a o~a)\n" (string->symbol kebab)
          (string-join (for/list ([t margs] [i (in-naturals)]) (format " v~a" i)) ""))
       (p "  (require-alive! '~a o)\n" (string->symbol kebab))
       (p "  (ok! '~a (raw:~a~a)))\n\n"
          (string->symbol kebab) (string->symbol kebab) call-args)]))

  (get-output-string out))

;; ---- driver -----------------------------------------------------------------

(module+ main
  (define argv (current-command-line-arguments))
  (when (zero? (vector-length argv))
    (error 'generate "usage: racket tools/generator/generate.rkt <spec.json> ..."))
  (define repo-root
    (simplify-path
     (build-path (path-only (path->complete-path (find-system-path 'run-file))) ".." "..")))
  (for ([spec-path (in-vector argv)])
    (define spec (with-input-from-file spec-path read-json))
    (define module (hash-ref spec 'module))
    (define gen-shim (build-path repo-root "bezel-shim" "src" "generated"))
    (define gen-rkt (build-path repo-root "bezel-lib" "generated"))
    (make-directory* gen-shim)
    (make-directory* gen-rkt)
    (display-to-file (emit-shim spec) (build-path gen-shim (~a module "_gen.cpp")) #:exists 'replace)
    (display-to-file (emit-racket spec) (build-path gen-rkt (~a module "_gen.rkt")) #:exists 'replace)
    (printf "generate: ~a -> <~a>_gen.cpp + <~a>_gen.rkt\n" (hash-ref spec 'class) module module)))
