#lang racket/base

;; Bezel binding generator: JSON class specs → C++ shim + Racket FFI.
;;
;; The handwritten core covers the common widgets with hand-tuned
;; ergonomics. The long tail of Qt coverage is spec-driven. Generated
;; bindings must preserve the same invariants as handwritten bindings:
;;
;;   - every Qt call enters C++ from Bezel's GUI marshal layer
;;   - object and widget arguments are liveness-checked
;;   - failed native calls surface exn:fail:bezel, including sentinel
;;     numeric return values such as -1
;;   - nullable parent handles remain nullable; non-null bad handles fail
;;
;; Usage:
;;   racket tools/generator/generate.rkt tools/generator/specs/*.json

(require json
         racket/file
         (only-in racket/path path-only)
         racket/format
         racket/list
         racket/match
         racket/port
         racket/string)

;; ---- type maps -------------------------------------------------------------

(define (cpp-type t)
  (match t
    ["parent" "bezel_handle"]
    ["widget" "bezel_handle"]
    ["string" "const char*"]
    ["int"    "int"]
    ["double" "double"]
    ["bool"   "int"]
    [_ (error 'generate "unsupported argument type: ~a" t)]))

(define (cpp-ret t)
  (match t
    ["string" "const char*"]
    ["int"    "int"]
    ["double" "double"]
    ["bool"   "int"]
    [_ (error 'generate "unsupported return type: ~a" t)]))

(define (rkt-type t)
  (match t
    ["parent" "_bezel-handle"]
    ["widget" "_bezel-handle"]
    ["string" "_string/utf-8"]
    ["int"    "_int"]
    ["double" "_double"]
    ["bool"   "_int"]
    [_ (error 'generate "unsupported argument type: ~a" t)]))

(define (cpp-pass t i)
  (match t
    ["string" (format "q_str~a" i)]
    ["bool"   (format "(in~a != 0)" i)]
    ["parent" (format "parent~a" i)]
    ["widget" (format "widget~a" i)]
    [_        (format "in~a" i)]))

(define (rkt-pass t i)
  (match t
    ["bool"   (format "(if v~a 1 0)" i)]
    ["parent" (format "(and v~a (ptr-of v~a))" i i)]
    ["widget" (format "(and v~a (ptr-of v~a))" i i)]
    [_        (format "v~a" i)]))

(define (emit-cpp-arg-prelude p args what indent)
  (for ([t args] [i (in-naturals)])
    (match t
      ["string"
       (p "~aconst QString q_str~a = QString::fromUtf8(in~a ? in~a : \"\");\n"
          indent i i i)]
      ["parent"
       (p "~aQWidget* parent~a = resolve_parent(in~a, \"~a\");\n"
          indent i i what)
       (p "~aif (in~a && !parent~a) return nullptr;\n" indent i i)]
      ["widget"
       (p "~aQWidget* widget~a = resolve_as<QWidget>(in~a, \"~a\");\n"
          indent i i what)
       (p "~aif (!widget~a) return ~a;\n"
          indent i "0")]
      [_ (void)])))

;; ---- shim emitter ----------------------------------------------------------

(define (emit-shim spec)
  (define class (hash-ref spec 'class))
  (define module (hash-ref spec 'module))
  (define header (hash-ref spec 'header))
  (define ctors (hash-ref spec 'constructors '()))
  (define methods (hash-ref spec 'methods '()))
  (define out (open-output-string))
  (define (p . xs) (apply fprintf out xs))

  (p "// <~a>_gen.cpp — generated by tools/generator; edit the spec instead.\n\n" module)
  (p "#include \"../internal.h\"\n\n#include <~a>\n\n" header)
  (p "namespace {\n\nusing namespace bezel;\n\n")
  (p "~a* resolve_obj(bezel_handle h, const char* what) {\n" class)
  (p "    return resolve_as<~a>(h, what);\n}\n\n" class)
  (p "QWidget* resolve_parent(bezel_handle h, const char* what) {\n")
  (p "    return h ? resolve_as<QWidget>(h, what) : nullptr;\n}\n\n")
  (p "}  // namespace\n\nusing namespace bezel;\n\nextern \"C\" {\n\n")

  ;; constructors
  (for ([c ctors])
    (define cname (string-replace (hash-ref c 'c-name) "-" "_"))
    (define args (hash-ref c 'args '()))
    (p "BEZEL_EXPORT bezel_handle ~a(" cname)
    (unless (null? args)
      (p (string-join
          (for/list ([t args] [i (in-naturals)])
            (format "~a in~a" (cpp-type t) i))
          ", ")))
    (p ") {\n")
    (p "    return on_gui([=]() -> bezel_handle {\n")
    ;; Constructors return a pointer, so emit parent/widget checks here
    ;; rather than using the generic method prelude's integer sentinel.
    (for ([t args] [i (in-naturals)])
      (match t
        ["string"
         (p "        const QString q_str~a = QString::fromUtf8(in~a ? in~a : \"\");\n"
            i i i)]
        ["parent"
         (p "        QWidget* parent~a = resolve_parent(in~a, \"~a\");\n" i i cname)
         (p "        if (in~a && !parent~a) return nullptr;\n" i i)]
        ["widget"
         (p "        QWidget* widget~a = resolve_as<QWidget>(in~a, \"~a\");\n" i i cname)
         (p "        if (!widget~a) return nullptr;\n" i)]
        [_ (void)]))
    (define ctor-args
      (string-join
       (for/list ([t args] [i (in-naturals)]) (cpp-pass t i))
       ", "))
    (p "        return register_object(new ~a(~a));\n" class ctor-args)
    (p "    });\n}\n\n"))

  ;; methods
  (for ([m methods])
    (define mname (string-replace (hash-ref m 'c-name) "-" "_"))
    (define qt (hash-ref m 'qt))
    (define margs (hash-ref m 'args '()))
    (define ret (hash-ref m 'ret #f))
    (p "BEZEL_EXPORT ~a ~a(bezel_handle h~a) {\n"
       (if ret (cpp-ret ret) "int")
       mname
       (string-join
        (for/list ([t margs] [i (in-naturals)])
          (format ", ~a in~a" (cpp-type t) i))
        ""))
    (p "    return on_gui([=]() -> ~a {\n" (if ret (cpp-ret ret) "int"))
    (p "        ~a* obj = resolve_obj(h, \"~a\");\n" class mname)
    (p "        if (!obj) return ~a;\n"
       (cond
         [(not ret) "0"]
         [(equal? ret "double") "-1.0"]
         [(equal? ret "string") "nullptr"]
         [else "-1"]))
    (for ([t margs] [i (in-naturals)])
      (match t
        ["string"
         (p "        const QString q_str~a = QString::fromUtf8(in~a ? in~a : \"\");\n"
            i i i)]
        ["parent"
         (p "        QWidget* parent~a = resolve_parent(in~a, \"~a\");\n" i i mname)
         (p "        if (in~a && !parent~a) return ~a;\n"
            i i
            (cond [(not ret) "0"]
                  [(equal? ret "double") "-1.0"]
                  [(equal? ret "string") "nullptr"]
                  [else "-1"]))]
        ["widget"
         (p "        QWidget* widget~a = resolve_as<QWidget>(in~a, \"~a\");\n" i i mname)
         (p "        if (!widget~a) return ~a;\n"
            i
            (cond [(not ret) "0"]
                  [(equal? ret "double") "-1.0"]
                  [(equal? ret "string") "nullptr"]
                  [else "-1"]))]
        [_ (void)]))
    (define call-args
      (string-join
       (for/list ([t margs] [i (in-naturals)]) (cpp-pass t i))
       ", "))
    (cond
      [ret
       (match ret
         ["string" (p "        return strdup_q(obj->~a(~a));\n" qt call-args)]
         ["bool"   (p "        return obj->~a(~a) ? 1 : 0;\n" qt call-args)]
         [_        (p "        return obj->~a(~a);\n" qt call-args)])]
      [else
       (p "        obj->~a(~a);\n" qt call-args)
       (p "        return 1;\n")])
    (p "    });\n}\n\n"))

  (p "}  // extern \"C\"\n\n")
  (get-output-string out))

;; ---- Racket emitter --------------------------------------------------------

(define (emit-racket spec)
  (define ctors (hash-ref spec 'constructors '()))
  (define methods (hash-ref spec 'methods '()))
  (define module (hash-ref spec 'module))
  (define out (open-output-string))
  (define (p . xs) (apply fprintf out xs))

  (p "#lang racket/base\n\n")
  (p ";; Generated by tools/generator from specs/~a.json — edit the spec.\n\n" module)
  (p "(provide")
  (for ([c ctors]) (p "\n         ~a" (hash-ref c 'c-name)))
  (for ([m methods]) (p "\n         ~a" (hash-ref m 'c-name)))
  (p ")\n\n")
  (p "(require ffi/unsafe\n")
  (p "         \"../private/ctypes.rkt\"\n")
  (p "         \"../private/errors.rkt\"\n")
  (p "         \"../private/lib.rkt\"\n")
  (p "         \"../private/marshal.rkt\"\n")
  (p "         \"../private/objects.rkt\"\n")
  (p "         (only-in \"../private/raw.rkt\" bezel-free))\n\n")
  (p ";; Direct FFI procedures are private to this generated module. Every\n")
  (p ";; public operation enters them through `gui`, matching handwritten\n")
  (p ";; Bezel bindings and preserving free-threaded public semantics.\n\n")

  (for ([c ctors])
    (define kebab (hash-ref c 'c-name))
    (define snake (string-replace kebab "-" "_"))
    (define args (hash-ref c 'args '()))
    (define has-parent (member "parent" args))
    (define parent-idx (and has-parent (index-of args "parent")))
    (p "(define ffi:~a (get-ffi-obj '~a bezel-lib (_fun ~a -> _bezel-handle)))\n"
       kebab snake (string-join (for/list ([t args]) (rkt-type t)) " "))
    (p "(define (~a~a)\n" kebab
       (string-join
        (for/list ([t args] [i (in-naturals)])
          (format " [v~a ~a]" i
                  (match t
                    ["string" "\"\""]
                    ["double" "0.0"]
                    ["int" "0"]
                    [_ "#f"])))
        ""))
    (p "  (require-application)\n")
    (for ([t args] [i (in-naturals)]
          #:when (or (equal? t "parent") (equal? t "widget")))
      (p "  (when v~a (require-alive! '~a v~a))\n" i (string->symbol kebab) i))
    (p "  (define ptr\n")
    (p "    (gui (lambda () (ffi:~a~a))))\n"
       (string->symbol kebab)
       (string-join
        (for/list ([t args] [i (in-naturals)])
          (format " ~a" (rkt-pass t i)))
        ""))
    (p "  (wrap-handle (ok-handle '~a ptr)\n" (string->symbol kebab))
    (p "               'widget ~a))\n\n"
       (if has-parent (format "(not v~a)" parent-idx) "#t")))

  (for ([m methods])
    (define kebab (hash-ref m 'c-name))
    (define snake (string-replace kebab "-" "_"))
    (define margs (hash-ref m 'args '()))
    (define ret (hash-ref m 'ret #f))
    (define params
      (string-join
       (for/list ([t margs] [i (in-naturals)]) (format " v~a" i))
       ""))
    (define call-args
      (string-join
       (for/list ([t margs] [i (in-naturals)])
         (format " ~a" (rkt-pass t i)))
       ""))
    (p "(define ffi:~a (get-ffi-obj '~a bezel-lib (_fun _bezel-handle~a -> ~a)))\n"
       kebab snake
       (string-join (for/list ([t margs]) (format " ~a" (rkt-type t))) "")
       (match ret
         ["string" "_pointer"]
         [_ (if ret (rkt-type ret) "_int")]))
    (p "(define (~a o~a)\n" (string->symbol kebab) params)
    (p "  (require-alive! '~a o)\n" (string->symbol kebab))
    (for ([t margs] [i (in-naturals)]
          #:when (or (equal? t "parent") (equal? t "widget")))
      (p "  (when v~a (require-alive! '~a v~a))\n" i (string->symbol kebab) i))
    (p "  (define r\n")
    (p "    (gui (lambda () (ffi:~a (ptr-of o)~a))))\n"
       (string->symbol kebab) call-args)
    (cond
      [(equal? ret "string")
       (p "  (define ptr (ok-string '~a r))\n" (string->symbol kebab))
       (p "  (begin0 (cstring->string/utf8 ptr)\n")
       (p "    (bezel-free ptr)))\n\n")]
      [(equal? ret "bool")
       (p "  (cond [(= r -1) (raise-bezel-error '~a)]\n" (string->symbol kebab))
       (p "        [(= r 1) #t]\n")
       (p "        [else #f]))\n\n")]
      [ret
       (p "  (when (and (= r ~a) (last-error))\n"
          (if (equal? ret "double") "-1.0" "-1"))
       (p "    (raise-bezel-error '~a))\n" (string->symbol kebab))
       (p "  r)\n\n")]
      [else
       (p "  (ok! '~a r))\n\n" (string->symbol kebab))]))

  (get-output-string out))

;; ---- driver ----------------------------------------------------------------

(module+ main
  (define argv (current-command-line-arguments))
  (when (zero? (vector-length argv))
    (error 'generate "usage: racket tools/generator/generate.rkt <spec.json> ..."))
  (define repo-root
    (simplify-path
     (build-path (path-only (path->complete-path (find-system-path 'run-file))) ".." "..")))
  (for ([spec-path (in-vector argv)])
    (define spec (with-input-from-file spec-path read-json))
    (define module (hash-ref spec 'module))
    (define gen-shim (build-path repo-root "bezel-shim" "src" "generated"))
    (define gen-rkt (build-path repo-root "bezel-lib" "generated"))
    (make-directory* gen-shim)
    (make-directory* gen-rkt)
    (display-to-file (emit-shim spec)
                     (build-path gen-shim (~a module "_gen.cpp"))
                     #:exists 'replace)
    (display-to-file (emit-racket spec)
                     (build-path gen-rkt (~a module "_gen.rkt"))
                     #:exists 'replace)
    (printf "generate: ~a -> <~a>_gen.cpp + <~a>_gen.rkt\n"
            (hash-ref spec 'class) module module)))
